spring:
  application:
    name: devjobs
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:devjobs;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
management:
  endpoints.web.exposure.include: "health,info"
server:
  port: 8080
