name: CI (Maven)

on:
  push: { branches: [master, feat/**, fix/**, chore/**] }
  pull_request: { branches: [master] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw -B -ntp clean package -DskipTests
